#!/usr/bin/env python3
"""세션 수확기 — `_NIGHT.md` §4.1 수확 단계의 결정론 부분.

여러 저장소(Claude Code · gjc)에서 지정 프로젝트의 최근 세션을 찾아,
컨텍스트 위생 규칙에 맞는 다이제스트 파일로 떨군다.

왜 스크립트인가: 새벽 1:30 에이전트는 맥락 제로다. 저장소 위치·스키마·
오탐 함정을 프롬프트로 설명하면 매번 다르게 해석한다. 판별은 여기서 얼리고,
에이전트는 다이제스트만 읽는다.

  python3 .claude/vault/backlog/harvest.py --dry-run     # 표만 출력, 쓰기 없음
  python3 .claude/vault/backlog/harvest.py               # 다이제스트 생성

일반 실행은 `<out>/runs/<run_id>/`에만 산출물을 쓴다. `run_id`는
`--run-id`로 재개할 수 있고, 생략하면 `run-<UTC timestamp>-<uuid>`로 만든다.
`index.json`, `rejections.md`, 다이제스트의 메타데이터, `.stamp-candidate`에는
실행(run), 원천(source), 세션(session) 식별자가 함께 들어간다. 마지막에
`.run-complete.json`을 원자적으로 교체한 경우에만 실행을 완료한 것으로 본다.
완료 표식의 해시·식별자가 맞을 때만 `--commit-success --run-id <id>`가
성공 도장을 확정한다. 표식이 없거나 산출물이 바뀌면 `committable=false`다.
"""
import argparse
import datetime as dt
import glob
import hashlib
import json
import math
import os
import re
import sys
import uuid

HOME = os.path.expanduser("~")
UTC = dt.timezone.utc

# 실제 Skill 호출만 인정한다. 느슨한 부분일치(`command-name>` 안에 warp/wrap)를
# 쓰면 밤 계약 본문을 읽은 세션이 전부 "warp 완료"로 오탐된다 — 이 파일과
# 수확 단계를 논의한 세션일수록 수확에서 사라지는 자기참조 함정.
# 실측 형태: "name":"Skill","input":{"skill":"wrap"}   (2026-08-11 warp로 개명)
WARP_CALL = re.compile(r'"name"\s*:\s*"Skill"\s*,\s*"input"\s*:\s*\{\s*"skill"\s*:\s*"(warp|wrap)"')

# 러너/sweep 단계 자신의 세션은 "첫 발화"로만 판정한다. 본문 어디든 파일명이
# 있으면 스킵하는 규칙은 위와 같은 오탐을 만든다.
BOOT_PHRASE = re.compile(r'_(RUNNER|SWEEP)\.md\s*(를|을)?\s*읽고')

ASSISTANT_CAP = 500   # assistant 텍스트 절단 (원출력 대량 인용 금지)
DIGEST_CAP = 50_000   # 초과 시 서브에이전트 위임 대상으로 표시

# user 롤로 도착하지만 사람이 친 게 아닌 것들 — 스킬 본문·훅 주입·압축 요약.
# 실측(2026-08-11, 17세션/157발화): 3000자 초과 10건이 user 텍스트 부피의 95%였고
# 그 10건이 전부 주입물이었다. 사람 발화는 전원 3000자 미만.
# 주입원을 일일이 열거하면 훅이 늘 때마다 깨지므로 길이 상한을 1차 방어선으로 쓴다.
USER_CAP = 3000
INJECTED_PREFIXES = (
    "Base directory for this skill:",
    "Caveat: The messages below were generated by the user while running local commands",
    "This session is being continued from a previous conversation",
)

# 기각 순간 — 대화에서 재사용 가치가 있는 유일한 고신호 구간.
#
# 원본 트랜스크립트 전체는 노이즈다("무엇을 했는가"만 남고 "왜 그걸 골랐는가"는 안 남는다).
# 재사용되는 건 **사람이 제안을 되돌린 순간**이다 — 동의("ㅇㅇ 진행")엔 정보가 거의 없고,
# 기각·되물음에 판단 기준이 압축돼 있다. 원자료 위에 얹는 정제된 중간 표현.
#
# 여기서는 **후보만 넓게 긁는다**(재현율 우선). 진짜 기각인지 판정은 LLM이 한다 —
# 싸게 전수 열거하고 비싸게 판정하는 2층 구조.
REJECT_MARKERS = re.compile(
    r"아닌데|아니라|아니고|아니야|아니에|^아니|ㄴㄴ|말고|빼고|"
    r"이해\s*못|이해못|모르겠|뭔\s*말|무슨\s*말|뭔소리|어렵|"
    r"잘못|틀렸|틀린|이상한|이상함|구림|구린|별로|아쉬|부족|"
    r"다시|재작성|재구성|고쳐|바꿔|"
    r"맞음\?|맞나|맞아\?|이게\s*맞|왜\s|왜\?|"
    r"미안한데|솔직히|근데\s",
    re.M,
)
# 승인으로 시작하는 발화는 기각이 아니다. 실측(2026-08-11)에서 "좋은듯?", "오오오 내가원한게
# 딱 이런표임" 같은 명백한 동의가 뒤에 붙은 "근데/?" 때문에 기각으로 잡혔다.
APPROVE_HEAD = re.compile(r"^\s*(좋|오오|굿|ㅇㅇ|넵|넵넵|오케|오키|ok|OK|완벽|훌륭|나이스|짱)")


def _iter_json(path):
    with open(path, encoding="utf-8", errors="ignore") as fh:
        for line in fh:
            try:
                yield json.loads(line)
            except Exception:
                continue


def _texts(content):
    """content 배열에서 순수 text 블록만. thinking/tool_use/tool_result 제외."""
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        return ""
    return "".join(
        b.get("text", "") for b in content
        if isinstance(b, dict) and b.get("type") == "text"
    )


def _turns_claude(path):
    """Claude Code 스키마: {"type":"user"|"assistant","message":{"content":[...]}}"""
    for o in _iter_json(path):
        t = o.get("type")
        if t not in ("user", "assistant"):
            continue
        msg = o.get("message")
        if not isinstance(msg, dict):
            continue
        txt = _texts(msg.get("content"))
        if txt.strip():
            yield t, txt.strip()


def _turns_gjc(path):
    """gjc 스키마: {"type":"message","message":{"role":"user"|"assistant"|"toolResult"}}"""
    for o in _iter_json(path):
        msg = o.get("message")
        if not isinstance(msg, dict):
            continue
        role = msg.get("role")
        if role not in ("user", "assistant"):   # toolResult 제외
            continue
        txt = _texts(msg.get("content"))
        if txt.strip():
            yield role, txt.strip()


def short_id(sid):
    """세션 식별자 8자. gjc 파일명은 `<ISO타임스탬프>_<uuid>` 라서 앞 8자를 쓰면
    같은 날 세션이 전부 `2026-08-` 로 충돌한다 — uuid 쪽을 쓴다."""
    return (sid.rsplit("_", 1)[-1] if "_" in sid else sid)[:8]


def _gjc_cwd(path, limit=300):
    for i, o in enumerate(_iter_json(path)):
        if i > limit:
            break
        if o.get("cwd"):
            return o["cwd"]
    return None


def parse_now(value):
    """명시적 기준 시각을 UTC epoch로 바꾼다. 시간대 없는 값은 거부한다."""
    if value is None:
        return dt.datetime.now(UTC).timestamp()
    normalized = value.replace("Z", "+00:00")
    parsed = dt.datetime.fromisoformat(normalized)
    if parsed.tzinfo is None:
        raise ValueError("기준 시각에 시간대가 없다. Z 또는 +00:00을 붙여라")
    return parsed.astimezone(UTC).timestamp()


def _atomic_write(path, text):
    """같은 디렉터리에서 교체해 부분 파일을 노출하지 않는다."""
    parent = os.path.dirname(path) or "."
    os.makedirs(parent, exist_ok=True)
    temporary = f"{path}.tmp-{os.getpid()}-{uuid.uuid4().hex}"
    try:
        with open(temporary, "w", encoding="utf-8") as fh:
            fh.write(text)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(temporary, path)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass


def _sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _json_text(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def read_stamp(path, now=None):
    """성공 도장을 읽는다.

    도장은 유한한 0 이상 숫자 epoch만 허용한다. 날짜 문자열이나 손상된
    숫자를 조용히 살리면 세션 창이 줄어들어 누락되므로 호출자가 복구해야
    하는 오류로 올린다.
    """
    with open(path, encoding="utf-8") as fh:
        raw = fh.read().strip()
    if not raw:
        raise ValueError("도장 파일이 비어 있다")
    head = raw.split()[0]
    try:
        epoch = float(head)
    except ValueError as exc:
        raise ValueError("도장은 숫자 epoch여야 한다") from exc
    if not math.isfinite(epoch) or epoch < 0:
        raise ValueError("도장 epoch가 유한한 0 이상 숫자가 아니다")
    if now is not None and epoch > now:
        raise ValueError("도장이 기준 시각보다 미래다")
    return epoch


def write_stamp(path, epoch):
    """도장을 쓴다. 숫자 뒤에 사람이 읽는 날짜를 주석으로 붙여
    '이게 무슨 파일인지 몰라서 날짜 글자로 덮어쓰는' 사고를 막는다."""
    when = dt.datetime.fromtimestamp(epoch, UTC)
    _atomic_write(
        path,
        f"{epoch}  # {when:%Y-%m-%dT%H:%M:%SZ} — 첫 숫자만 읽는다. "
        f"손으로 고칠 때 숫자를 날짜 글자로 바꾸지 마라(2026-08-14 실사고)\n",
    )


def discover(project, since_h, exclude_recent_min, now):
    """저장소별로 후보 세션을 모은다. 반환: dict 리스트."""
    win_start = now - since_h * 3600
    cutoff = now - exclude_recent_min * 60
    out = []

    # --- Claude Code: 디렉토리명이 인코딩된 프로젝트 경로 ---
    enc = project.replace("/", "-")
    for p in glob.glob(f"{HOME}/.claude/projects/{enc}/*.jsonl"):
        out.append({"store": "claude", "path": p, "turns": _turns_claude})

    # --- gjc: 디렉토리명이 해시다. 프로젝트는 파일 안 cwd 로만 판별 ---
    #   (읽기 좋은 sessions/-projects-<name>/ 은 구형 경로 — 오늘 것은 여기 안 들어온다)
    for p in glob.glob(f"{HOME}/.gjc/agent/sessions/*/*.jsonl"):
        if os.path.getmtime(p) < win_start:
            continue          # cwd 파싱 전에 싸게 거른다
        if _gjc_cwd(p) == project:
            out.append({"store": "gjc", "path": p, "turns": _turns_gjc})

    sessions = []
    for c in out:
        p = c["path"]
        m = os.path.getmtime(p)
        rec = {
            "store": c["store"],
            "sid": os.path.basename(p)[:-6],
            "path": p,
            "mtime": m,
            "size_kb": os.path.getsize(p) // 1024,
            "_turns": c["turns"],
        }
        if not (win_start <= m):
            rec["verdict"] = "skip:창밖"
        elif m > cutoff:
            rec["verdict"] = "skip:작업중"
        else:
            raw = open(p, encoding="utf-8", errors="ignore").read()
            first_user = next((t for r, t in c["turns"](p) if r == "user" and not t.startswith("<")), "")
            rec["first_user"] = first_user[:200]
            if WARP_CALL.search(raw):
                rec["verdict"] = "skip:warp완료"
            elif BOOT_PHRASE.search(first_user):
                rec["verdict"] = "skip:러너/sweep 단계"
            else:
                rec["verdict"] = "TARGET"
        sessions.append(rec)

    sessions.sort(key=lambda r: -r["mtime"])
    return sessions


def digest(rec, metadata=None):
    """세션 1개 → 다이제스트 텍스트. user 전문 + assistant 500자 절단."""
    lines = []
    if metadata is not None:
        lines.extend([f"<!-- harvest-metadata: {_json_text(metadata)} -->", ""])
    lines.extend([
        f"# 세션 다이제스트 — {rec['store']}:{short_id(rec['sid'])}",
        "",
        f"- 저장소: `{rec['path']}`",
        f"- 최종 수정: {dt.datetime.fromtimestamp(rec['mtime'], UTC):%Y-%m-%dT%H:%MZ}  ({rec['size_kb']}KB)",
        "",
        "> user 발화는 전문, assistant는 500자 절단. thinking·tool_use·tool_result 제외.",
        "",
    ])
    for role, txt in rec["_turns"](rec["path"]):
        if role == "user":
            if txt.startswith("<"):        # system-reminder·cross-session-message 등
                continue
            if txt.startswith(INJECTED_PREFIXES):
                continue
            if len(txt) > USER_CAP:        # 붙여넣기 폭탄·미지의 주입원 방어
                txt = txt[:USER_CAP] + f" …(+{len(txt)-USER_CAP}자 절단)"
            lines.append(f"\n## USER\n{txt}")
        else:
            t = txt[:ASSISTANT_CAP]
            if len(txt) > ASSISTANT_CAP:
                t += f" …(+{len(txt)-ASSISTANT_CAP}자)"
            lines.append(f"\n### assistant\n{t}")
    return "\n".join(lines)


def rejections(rec):
    """(직전 제안, 사람의 기각) 쌍을 뽑는다.

    기각 발화만 떼어놓으면 "무엇을 기각했는지"가 사라지므로 반드시 쌍으로 남긴다 —
    재사용되는 최소 단위가 쌍이다."""
    out, prev = [], None
    for role, txt in rec["_turns"](rec["path"]):
        if role == "user":
            if txt.startswith("<") or txt.startswith(INJECTED_PREFIXES):
                continue
            if (len(txt) <= USER_CAP and REJECT_MARKERS.search(txt)
                    and not APPROVE_HEAD.match(txt)):
                out.append({"proposal": (prev or "")[:400], "rejection": txt[:800]})
        else:
            prev = txt
    return out


def _project_identity(path):
    return os.path.realpath(os.path.abspath(os.path.expanduser(path)))


def _new_run_id(now):
    stamp = dt.datetime.fromtimestamp(now, UTC).strftime("%Y%m%dT%H%M%SZ")
    return f"run-{stamp}-{uuid.uuid4()}"


def _session_identity(rec):
    return {
        "source": rec["store"],
        "session_id": rec["sid"],
        "session_path": rec["path"],
    }


def _safe_artifact_path(run_dir, relative):
    if not isinstance(relative, str) or not relative or os.path.isabs(relative):
        raise ValueError("완료 표식의 산출물 경로가 상대 경로가 아니다")
    normalized = os.path.normpath(relative)
    if normalized != relative or normalized == ".." or normalized.startswith(f"..{os.sep}"):
        raise ValueError("완료 표식의 산출물 경로가 실행 디렉터리 밖이다")
    path = os.path.abspath(os.path.join(run_dir, normalized))
    root = os.path.abspath(run_dir)
    if path != root and not path.startswith(root + os.sep):
        raise ValueError("완료 표식의 산출물 경로가 실행 디렉터리 밖이다")
    return path


def _artifact_paths(run_dir, index_data):
    paths = {"index.json", "rejections.md", ".stamp-candidate"}
    sessions = index_data.get("sessions")
    if not isinstance(sessions, list):
        raise ValueError("index.json의 sessions가 목록이 아니다")
    for session in sessions:
        if not isinstance(session, dict):
            raise ValueError("index.json의 session 항목이 객체가 아니다")
        relative = session.get("digest")
        _safe_artifact_path(run_dir, relative)
        paths.add(relative)
    return sorted(paths)


def _artifact_hashes(run_dir, index_data):
    hashes = {}
    for relative in _artifact_paths(run_dir, index_data):
        path = _safe_artifact_path(run_dir, relative)
        if not os.path.isfile(path):
            raise ValueError(f"산출물이 없다: {relative}")
        hashes[relative] = _sha256(path)
    return hashes


def _read_json_file(path, label):
    try:
        with open(path, encoding="utf-8") as fh:
            value = json.load(fh)
    except (OSError, ValueError) as exc:
        raise ValueError(f"{label}이(가) 올바른 JSON이 아니다") from exc
    if not isinstance(value, dict):
        raise ValueError(f"{label}이(가) 객체가 아니다")
    return value


def _read_candidate(path, now):
    try:
        with open(path, encoding="utf-8") as fh:
            lines = fh.read().splitlines()
    except OSError as exc:
        raise ValueError("도장 후보를 읽을 수 없다") from exc
    epoch = read_stamp(path, now=now)
    metadata_line = next(
        (line for line in lines[1:] if line.startswith("# harvest-metadata: ")),
        None,
    )
    if metadata_line is None:
        raise ValueError("도장 후보에 실행 메타데이터가 없다")
    try:
        metadata = json.loads(metadata_line[len("# harvest-metadata: "):])
    except ValueError as exc:
        raise ValueError("도장 후보 메타데이터가 올바른 JSON이 아니다") from exc
    if not isinstance(metadata, dict):
        raise ValueError("도장 후보 메타데이터가 객체가 아니다")
    return epoch, metadata


def _output_root(project, explicit_out, now):
    return explicit_out or os.path.join(
        project,
        ".claude/vault/backlog/sweep",
        dt.datetime.fromtimestamp(now, UTC).strftime("%Y-%m-%d"),
    )


def _run_dir(root, run_id):
    return os.path.join(root, "runs", run_id)


def _locate_run_dir(project, explicit_out, run_id, now):
    if explicit_out:
        return _run_dir(explicit_out, run_id)
    sweep_root = os.path.join(project, ".claude/vault/backlog/sweep")
    matches = glob.glob(os.path.join(sweep_root, "*", "runs", run_id))
    matches = [p for p in matches if os.path.isdir(p)]
    if len(matches) == 1:
        return matches[0]
    return _run_dir(_output_root(project, None, now), run_id)


def _existing_index(project, explicit_out, run_id, now):
    run_dir = _locate_run_dir(project, explicit_out, run_id, now)
    try:
        data = _read_json_file(os.path.join(run_dir, "index.json"), "index.json")
    except (OSError, ValueError):
        return None
    if data.get("run_id") != run_id or data.get("source") != project:
        return None
    return data


def _resume_now(project, explicit_out, run_id, requested_now):
    """같은 run-id를 재실행하면 최초 실행의 기준 시각을 유지한다."""
    data = _existing_index(project, explicit_out, run_id, requested_now)
    stored = data.get("now_epoch") if data else None
    if isinstance(stored, (int, float)) and math.isfinite(stored) and stored >= 0:
        return float(stored)
    return requested_now


def _identities_from_index(index_data):
    identities = []
    for session in index_data.get("sessions", []):
        if not isinstance(session, dict):
            raise ValueError("index.json의 session 항목이 객체가 아니다")
        source = session.get("source")
        session_id = session.get("session_id")
        if not isinstance(source, str) or not isinstance(session_id, str):
            raise ValueError("index.json에 source/session_id가 없다")
        identities.append({
            "source": source,
            "session_id": session_id,
            "session_path": session.get("session_path", ""),
        })
    return identities


def _validate_completed_run(run_dir, run_id, project, now):
    marker_path = os.path.join(run_dir, ".run-complete.json")
    if not os.path.isfile(marker_path):
        raise ValueError("완료 표식이 없다 — committable=false")
    marker = _read_json_file(marker_path, "완료 표식")
    if marker.get("run_id") != run_id:
        raise ValueError("완료 표식의 run_id가 요청과 다르다")
    if marker.get("source") != project:
        raise ValueError("완료 표식의 source가 현재 project와 다르다")
    if marker.get("committable") is not True:
        raise ValueError("완료 표식이 committable=true가 아니다")

    index = _read_json_file(os.path.join(run_dir, "index.json"), "index.json")
    if index.get("run_id") != run_id or index.get("source") != project:
        raise ValueError("index.json의 run/source 식별자가 맞지 않는다")
    identities = _identities_from_index(index)
    if marker.get("sessions") != identities:
        raise ValueError("완료 표식의 session 식별자가 맞지 않는다")

    candidate_path = os.path.join(run_dir, ".stamp-candidate")
    epoch, candidate = _read_candidate(candidate_path, now)
    if candidate.get("run_id") != run_id or candidate.get("source") != project:
        raise ValueError("도장 후보의 run/source 식별자가 맞지 않는다")
    if candidate.get("status") != "ready":
        raise ValueError("도장 후보가 ready 상태가 아니다")
    if candidate.get("sessions") != identities:
        raise ValueError("도장 후보의 session 식별자가 맞지 않는다")
    if candidate.get("candidate_epoch") != epoch:
        raise ValueError("도장 후보의 epoch 메타데이터가 첫 숫자와 다르다")

    expected = marker.get("artifacts")
    if not isinstance(expected, dict):
        raise ValueError("완료 표식에 산출물 hash가 없다")
    if marker.get("hashes") != expected:
        raise ValueError("완료 표식의 hash 필드가 서로 다르다")
    actual = _artifact_hashes(run_dir, index)
    if expected != actual:
        raise ValueError("산출물 hash가 완료 표식과 다르다 — committable=false")
    return epoch


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", default=os.getcwd())
    ap.add_argument("--since-hours", type=float, default=24)
    ap.add_argument("--exclude-recent-min", type=float, default=60)
    ap.add_argument("--out", default=None, help="기본: .claude/vault/backlog/sweep/<오늘>")
    ap.add_argument("--stamp-path", default=None,
                    help="성공 도장 경로. 기본: <project>/.claude/vault/backlog/sweep/.last-success")
    ap.add_argument("--now", default=None,
                    help="기준 시각 ISO 8601 (Z 또는 +00:00 필수, 드라이런 시뮬레이션용)")
    ap.add_argument("--run-id", default=None,
                    help="실행 식별자. 재개·commit-success 시 같은 값을 사용한다")
    ap.add_argument("--dry-run", action="store_true", help="표만 출력, 파일 안 씀")
    ap.add_argument("--commit-success", action="store_true",
                    help="완료된 run-id의 도장 후보를 실제 성공 도장으로 확정한다")
    a = ap.parse_args()

    try:
        now = parse_now(a.now)
    except ValueError as exc:
        print(f"✗ 기준 시각 오류: {exc}")
        return 2

    project = _project_identity(a.project)
    existing_index = None
    if not a.commit_success and a.run_id and not a.now:
        existing_index = _existing_index(project, a.out, a.run_id, now)
        now = _resume_now(project, a.out, a.run_id, now)
    stamp = a.stamp_path or os.path.join(
        project, ".claude/vault/backlog/sweep", ".last-success"
    )

    if a.commit_success:
        if a.dry_run:
            print("✗ --dry-run과 --commit-success를 함께 쓸 수 없다")
            return 2
        if not a.run_id:
            print("✗ --commit-success에는 --run-id가 필요하다")
            return 2
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}", a.run_id):
            print("✗ run-id 형식이 올바르지 않다")
            return 2
        run_dir = _locate_run_dir(project, a.out, a.run_id, now)
        try:
            epoch = _validate_completed_run(run_dir, a.run_id, project, now)
        except (OSError, ValueError) as exc:
            print(f"✗ 완료된 수확이 아니다: {exc}")
            return 1
        write_stamp(stamp, epoch)
        print(f"✓ 성공 도장 확정 {dt.datetime.fromtimestamp(epoch, UTC):%Y-%m-%dT%H:%M:%SZ} → {stamp}")
        return 0

    if a.run_id and not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}", a.run_id):
        print("✗ run-id 형식이 올바르지 않다")
        return 2
    run_id = a.run_id or _new_run_id(now)

    # Failsafe — 창을 "마지막 성공 이후"로 늘린다.
    # 고정 24시간이면 sweep 단계가 하루라도 못 뜬 날(맥북이 잠겼거나 실행이 죽었거나)
    # 그 사이 세션이 영영 안 걸린다. 창이 다음 날 이미 지나가 버리기 때문.
    # 마지막 성공 시각을 남겨두고 그 이후 전부를 훑으면 빠뜨림이 사라진다.
    since_h = a.since_hours
    exclude_recent_min = a.exclude_recent_min
    if existing_index is not None:
        stored_since = existing_index.get("since_hours")
        if isinstance(stored_since, (int, float)) and math.isfinite(stored_since) and stored_since >= 0:
            since_h = float(stored_since)
        stored_exclude = existing_index.get("exclude_recent_min")
        if (isinstance(stored_exclude, (int, float))
                and math.isfinite(stored_exclude) and stored_exclude >= 0):
            exclude_recent_min = float(stored_exclude)
    if os.path.exists(stamp):
        try:
            last = read_stamp(stamp, now=now)
            gap_h = (now - last) / 3600
            if gap_h > since_h:
                since_h = min(gap_h + 1, 24 * 14)   # 상한 2주 — 그 이상은 사람이 볼 일
                print(f"⚠ 마지막 성공이 {gap_h:.1f}시간 전 — 창을 {since_h:.1f}시간으로 넓힘 (건너뛴 날 복구)")
        except (OSError, ValueError) as exc:
            print(f"✗ 마지막 성공 시각을 읽을 수 없다: {exc}")
            return 2

    # 건너뛰기 경계 — discover() 안의 것과 같은 값. 도장 후보로 쓴다(맨 아래 주석 참조).
    cutoff = now - exclude_recent_min * 60
    sessions = discover(project, since_h, exclude_recent_min, now)
    targets = [s for s in sessions if s["verdict"] == "TARGET"]

    print(f"기준시각 {dt.datetime.fromtimestamp(now, UTC):%Y-%m-%dT%H:%MZ} · "
          f"창 {since_h:g}h · 최근 {exclude_recent_min:g}분 제외")
    print(f"{'store':7} {'sid':10} {'수정':12} {'크기':>8}  판정")
    for s in sessions:
        print(f"{s['store']:7} {short_id(s['sid']):10} "
              f"{dt.datetime.fromtimestamp(s['mtime'], UTC):%m-%dT%H:%MZ}  "
              f"{s['size_kb']:6d}KB  {s['verdict']}")
    by_store = {}
    for s in targets:
        by_store[s["store"]] = by_store.get(s["store"], 0) + 1
    print(f"\n대상 {len(targets)}개 / 스캔 {len(sessions)}개   {by_store}")

    if a.dry_run:
        print("\n(--dry-run: 파일 안 씀)")
        return 0

    out = _output_root(project, a.out, now)
    date = dt.datetime.fromtimestamp(now, UTC).strftime("%Y-%m-%d")
    run_dir = _run_dir(out, run_id)
    digest_dir = os.path.join(run_dir, "digest")
    os.makedirs(digest_dir, exist_ok=True)
    marker_path = os.path.join(run_dir, ".run-complete.json")
    try:
        os.unlink(marker_path)
    except FileNotFoundError:
        pass
    index, rej_all = [], []
    for s in targets:
        session_metadata = {
            "run_id": run_id,
            "source": s["store"],
            "session_id": s["sid"],
            "session_path": s["path"],
        }
        body = digest(s, session_metadata)
        name = f"{s['store']}-{short_id(s['sid'])}.md"
        digest_path = os.path.join(digest_dir, name)
        _atomic_write(digest_path, body)
        rj = rejections(s)
        rej_all.append((s, rj))
        index.append({
            "run_id": run_id,
            "source": s["store"],
            "session_id": s["sid"],
            "session_path": s["path"],
            "store": s["store"], "sid": s["sid"], "digest": f"digest/{name}",
            "mtime": dt.datetime.fromtimestamp(s["mtime"], UTC).isoformat(timespec="minutes"),
            "size_kb": s["size_kb"], "digest_bytes": len(body.encode()),
            "digest_sha256": _sha256(digest_path),
            "oversized": len(body.encode()) > DIGEST_CAP,
            "rejections": len(rj),
            "first_user": s.get("first_user", ""),
        })

    # 기각 순간 모음 — 후보만 긁은 것이라 진짜 기각인지는 LLM이 판정한다
    identities = [_session_identity(s) for s in targets]
    rejection_metadata = {
        "run_id": run_id,
        "source": project,
        "sessions": identities,
    }
    lines = [f"<!-- harvest-metadata: {_json_text(rejection_metadata)} -->", "",
             "# 기각 순간 후보 — 사람이 제안을 되돌린 자리", "",
             "> 어휘로 넓게 긁은 **후보**다(재현율 우선). 진짜 기각인지, 그 안에 담긴 판단 기준이",
             "> 무엇인지는 읽는 쪽이 판정한다. 동의는 정보가 없고 기각에 기준이 압축돼 있다는 전제.", ""]
    for s, rj in rej_all:
        if not rj:
            continue
        lines.append(f"\n## {s['store']}:{short_id(s['sid'])}  ({len(rj)}건)"
                     f" · source={s['store']} · session_id={s['sid']}")
        for i, r in enumerate(rj, 1):
            lines.append(f"\n**{i}. 직전 제안** — {r['proposal']}\n\n**→ 사람의 반응** — {r['rejection']}")
    rejections_text = "\n".join(lines) + "\n"
    _atomic_write(os.path.join(run_dir, "rejections.md"), rejections_text)

    index_data = {
        "run_id": run_id,
        "source": project,
        "generated_for": date,
        "generated_at": dt.datetime.fromtimestamp(now, UTC).isoformat(timespec="seconds"),
        "now_epoch": now,
        "project": project,
        "since_hours": since_h,
        "exclude_recent_min": exclude_recent_min,
        "scanned": len(sessions),
        "targets": len(targets),
        "sessions": index,
    }
    _atomic_write(
        os.path.join(run_dir, "index.json"),
        json.dumps(index_data, ensure_ascii=False, indent=2) + "\n",
    )
    over = sum(1 for i in index if i["oversized"])
    nrej = sum(i["rejections"] for i in index)
    print(f"\nrun_id {run_id}")
    print(f"다이제스트 {len(index)}개 → {digest_dir}/   (50KB 초과 {over}개 = 서브에이전트 위임 대상)")
    print(f"기각 순간 후보 {nrej}건 → {run_dir}/rejections.md")

    # 성공 도장은 여기서 찍지 않는다.
    #
    # 옛 동작: 수확이 끝나는 즉시 도장에 `now`(수확 시작 시각)를 찍었다. 두 가지가 고장나 있었다.
    #   ① 수확만 끝나고 노트·티켓·리포트가 하나도 없는 시점인데 "성공"으로 세어졌다.
    #      그래서 뒤 단계에서 죽으면 그 창의 대화가 통째로 사라졌다.
    #   ② 도장이 `now` 였는데 최근 N분은 "작업 중일 수 있다"고 건너뛴다. 즉 건너뛴 구간
    #      [now-N분, now] 는 다음 밤 창(= now 부터)에 안 들어간다. 매일 N분짜리 사각지대가
    #      생기고, 창을 넓히는 안전장치는 간격이 24시간을 못 넘어 영영 안 켜진다.
    #      2026-08-15 실사고 — 진짜 대화 5편(31MB)이 이 구멍에 빠질 뻔했다.
    #
    # 새 동작: 여기서는 **후보 시각만** 적어두고, 밤 루프가 리포트까지 다 낸 뒤
    # `--commit-success` 로 실제 도장을 찍는다. 후보 값은 `now` 가 아니라 **건너뛰기 경계**라,
    # 다음 밤 창이 이번에 건너뛴 지점에서 정확히 이어진다.
    candidate_metadata = {
        "run_id": run_id,
        "source": project,
        "sessions": identities,
        "candidate_epoch": cutoff,
        "status": "ready",
    }
    candidate_text = (
        f"{cutoff}  # {dt.datetime.fromtimestamp(cutoff, UTC):%Y-%m-%dT%H:%M:%SZ} "
        "= 이번 수확의 건너뛰기 경계. 완료 표식 검증 뒤 --commit-success 로 확정한다\n"
        f"# harvest-metadata: {_json_text(candidate_metadata)}\n"
    )
    _atomic_write(os.path.join(run_dir, ".stamp-candidate"), candidate_text)

    artifacts = _artifact_hashes(run_dir, index_data)
    marker = {
        "run_id": run_id,
        "source": project,
        "sessions": identities,
        "committable": True,
        "completed_at": dt.datetime.fromtimestamp(now, UTC).isoformat(timespec="seconds"),
        "artifacts": artifacts,
        "hashes": artifacts,
    }
    _atomic_write(marker_path, json.dumps(marker, ensure_ascii=False, indent=2) + "\n")
    print(f"\n도장 후보 {dt.datetime.fromtimestamp(cutoff, UTC):%Y-%m-%dT%H:%M:%SZ} → "
          f"{run_dir}/.stamp-candidate")
    print(f"완료 표식 {run_dir}/.run-complete.json (committable=true)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
