// 중앙 진행창과 채팅은 같은 상태 응답을 공유하고 늦은 응답은 다른 프로젝트에 섞이지 않는다.
import { afterEach, expect, it, vi } from 'vitest'
import { subscribeWriterStatus, readWriterStatus, restartWriterStatus } from '@/lib/writer/use-writer-status'
afterEach(() => { vi.unstubAllGlobals(); vi.useRealTimers() })
it('같은 작업의 중앙 진행 표시와 채팅 진행 표시는 같은 단계와 진행 상태를 보여준다.', async () => {
  vi.useFakeTimers()
  const fetcher = vi.fn().mockResolvedValue(new Response(JSON.stringify({ projectId: 'sync', started: true, current_stage: 'scenes' })))
  vi.stubGlobal('fetch', fetcher)
  const central: unknown[] = [], chat: unknown[] = []
  const stopA = subscribeWriterStatus('sync', () => central.push(readWriterStatus('sync').status))
  const stopB = subscribeWriterStatus('sync', () => chat.push(readWriterStatus('sync').status))
  await vi.advanceTimersByTimeAsync(1)
  expect(fetcher).toHaveBeenCalledTimes(1)
  expect(central.at(-1)).toBe(chat.at(-1))
  expect(readWriterStatus('sync').status?.current_stage).toBe('scenes')
  stopA(); stopB()
})
it('프로젝트를 바꾸면 늦게 도착한 이전 진행을 새 프로젝트에 표시하지 않는다.', async () => {
  vi.useFakeTimers()
  let finish!: (r: Response) => void
  vi.stubGlobal('fetch', vi.fn(() => new Promise<Response>(r => { finish = r })))
  const stop = subscribeWriterStatus('old', () => {})
  stop()
  finish(new Response(JSON.stringify({ projectId: 'old', current_stage: 'scenes' })))
  await vi.advanceTimersByTimeAsync(1)
  expect(readWriterStatus('old').status).toBeNull()
  expect(readWriterStatus('new').status).toBeNull()
})
it('멈춘 작업을 다시 시작하면 모든 진행 화면이 새 상태를 함께 받는다.', async () => {
  vi.useFakeTimers()
  const fetcher = vi.fn().mockImplementation(async () => new Response(JSON.stringify({ projectId: 'resume', started: true, pipeline_failed: fetcher.mock.calls.length === 1 })))
  vi.stubGlobal('fetch', fetcher)
  const stop = subscribeWriterStatus('resume', () => {})
  await vi.advanceTimersByTimeAsync(1)
  expect(readWriterStatus('resume').status?.pipeline_failed).toBe(true)
  restartWriterStatus('resume')
  await vi.advanceTimersByTimeAsync(1)
  expect(readWriterStatus('resume').status?.pipeline_failed).toBe(false)
  stop()
})
it('다시 시작한 작업의 첫 상태 확인에 실패해도 다음 확인을 계속한다.', async () => {
  vi.useFakeTimers()
  const fetcher = vi.fn()
    .mockResolvedValueOnce(Response.json({ projectId:'retry',started:true,pipeline_failed:true }))
    .mockRejectedValueOnce(new Error('temporary outage'))
    .mockResolvedValueOnce(Response.json({ projectId:'retry',started:true,pipeline_failed:false,current_stage:'scenes' }))
  vi.stubGlobal('fetch',fetcher)
  const stop=subscribeWriterStatus('retry',()=>{})
  await vi.advanceTimersByTimeAsync(1)
  restartWriterStatus('retry')
  await vi.advanceTimersByTimeAsync(3001)
  expect(fetcher).toHaveBeenCalledTimes(3)
  expect(readWriterStatus('retry').status?.pipeline_failed).toBe(false)
  stop()
})
