#!/usr/bin/env python3
"""세션 수확기 — 스위퍼(_SWEEP.md §1~2)의 결정론 부분.

여러 저장소(Claude Code · gjc)에서 지정 프로젝트의 최근 세션을 찾아,
컨텍스트 위생 규칙에 맞는 다이제스트 파일로 떨군다.

왜 스크립트인가: 새벽 1:30 에이전트는 맥락 제로다. 저장소 위치·스키마·
오탐 함정을 프롬프트로 설명하면 매번 다르게 해석한다. 판별은 여기서 얼리고,
에이전트는 다이제스트만 읽는다.

  python3 research/backlog/harvest.py --dry-run     # 표만 출력, 쓰기 없음
  python3 research/backlog/harvest.py               # 다이제스트 생성
"""
import argparse
import datetime as dt
import glob
import json
import os
import re
import sys

HOME = os.path.expanduser("~")

# 실제 Skill 호출만 인정한다. 느슨한 부분일치(`command-name>` 안에 warp/wrap)를
# 쓰면 _SWEEP.md 본문을 읽은 세션이 전부 "warp 완료"로 오탐된다 — 이 파일과
# 스위퍼 계약을 논의한 세션일수록 그물에서 사라지는 자기참조 함정.
# 실측 형태: "name":"Skill","input":{"skill":"wrap"}   (2026-08-11 warp로 개명)
WARP_CALL = re.compile(r'"name"\s*:\s*"Skill"\s*,\s*"input"\s*:\s*\{\s*"skill"\s*:\s*"(warp|wrap)"')

# 러너/스위퍼 자신의 세션은 "첫 발화"로만 판정한다. 본문 어디든 파일명이
# 있으면 스킵하는 규칙은 위와 같은 오탐을 만든다.
BOOT_PHRASE = re.compile(r'_(RUNNER|SWEEP)\.md\s*(를|을)?\s*읽고')

ASSISTANT_CAP = 500   # assistant 텍스트 절단 (원출력 대량 인용 금지)
DIGEST_CAP = 50_000   # 초과 시 서브에이전트 위임 대상으로 표시

# user 롤로 도착하지만 사람이 친 게 아닌 것들 — 스킬 본문·훅 주입·압축 요약.
# 실측(2026-08-11, 17세션/157발화): 3000자 초과 10건이 user 텍스트 부피의 95%였고
# 그 10건이 전부 주입물이었다. 사람 발화는 전원 3000자 미만.
# 주입원을 일일이 열거하면 훅이 늘 때마다 깨지므로 길이 상한을 1차 방어선으로 쓴다.
USER_CAP = 3000
INJECTED_PREFIXES = (
    "Base directory for this skill:",
    "Caveat: The messages below were generated by the user while running local commands",
    "This session is being continued from a previous conversation",
)

# 기각 순간 — 대화에서 재사용 가치가 있는 유일한 고신호 구간.
#
# 원본 트랜스크립트 전체는 노이즈다("무엇을 했는가"만 남고 "왜 그걸 골랐는가"는 안 남는다).
# 재사용되는 건 **사람이 제안을 되돌린 순간**이다 — 동의("ㅇㅇ 진행")엔 정보가 거의 없고,
# 기각·되물음에 판단 기준이 압축돼 있다. 원자료 위에 얹는 정제된 중간 표현.
#
# 여기서는 **후보만 넓게 긁는다**(재현율 우선). 진짜 기각인지 판정은 LLM이 한다 —
# 싸게 전수 열거하고 비싸게 판정하는 2층 구조.
REJECT_MARKERS = re.compile(
    r"아닌데|아니라|아니고|아니야|아니에|^아니|ㄴㄴ|말고|빼고|"
    r"이해\s*못|이해못|모르겠|뭔\s*말|무슨\s*말|뭔소리|어렵|"
    r"잘못|틀렸|틀린|이상한|이상함|구림|구린|별로|아쉬|부족|"
    r"다시|재작성|재구성|고쳐|바꿔|"
    r"맞음\?|맞나|맞아\?|이게\s*맞|왜\s|왜\?|"
    r"미안한데|솔직히|근데\s",
    re.M,
)
# 승인으로 시작하는 발화는 기각이 아니다. 실측(2026-08-11)에서 "좋은듯?", "오오오 내가원한게
# 딱 이런표임" 같은 명백한 동의가 뒤에 붙은 "근데/?" 때문에 기각으로 잡혔다.
APPROVE_HEAD = re.compile(r"^\s*(좋|오오|굿|ㅇㅇ|넵|넵넵|오케|오키|ok|OK|완벽|훌륭|나이스|짱)")


def _iter_json(path):
    with open(path, encoding="utf-8", errors="ignore") as fh:
        for line in fh:
            try:
                yield json.loads(line)
            except Exception:
                continue


def _texts(content):
    """content 배열에서 순수 text 블록만. thinking/tool_use/tool_result 제외."""
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        return ""
    return "".join(
        b.get("text", "") for b in content
        if isinstance(b, dict) and b.get("type") == "text"
    )


def _turns_claude(path):
    """Claude Code 스키마: {"type":"user"|"assistant","message":{"content":[...]}}"""
    for o in _iter_json(path):
        t = o.get("type")
        if t not in ("user", "assistant"):
            continue
        msg = o.get("message")
        if not isinstance(msg, dict):
            continue
        txt = _texts(msg.get("content"))
        if txt.strip():
            yield t, txt.strip()


def _turns_gjc(path):
    """gjc 스키마: {"type":"message","message":{"role":"user"|"assistant"|"toolResult"}}"""
    for o in _iter_json(path):
        msg = o.get("message")
        if not isinstance(msg, dict):
            continue
        role = msg.get("role")
        if role not in ("user", "assistant"):   # toolResult 제외
            continue
        txt = _texts(msg.get("content"))
        if txt.strip():
            yield role, txt.strip()


def short_id(sid):
    """세션 식별자 8자. gjc 파일명은 `<ISO타임스탬프>_<uuid>` 라서 앞 8자를 쓰면
    같은 날 세션이 전부 `2026-08-` 로 충돌한다 — uuid 쪽을 쓴다."""
    return (sid.rsplit("_", 1)[-1] if "_" in sid else sid)[:8]


def _gjc_cwd(path, limit=300):
    for i, o in enumerate(_iter_json(path)):
        if i > limit:
            break
        if o.get("cwd"):
            return o["cwd"]
    return None


def discover(project, since_h, exclude_recent_min, now):
    """저장소별로 후보 세션을 모은다. 반환: dict 리스트."""
    win_start = now - since_h * 3600
    cutoff = now - exclude_recent_min * 60
    out = []

    # --- Claude Code: 디렉토리명이 인코딩된 프로젝트 경로 ---
    enc = project.replace("/", "-")
    for p in glob.glob(f"{HOME}/.claude/projects/{enc}/*.jsonl"):
        out.append({"store": "claude", "path": p, "turns": _turns_claude})

    # --- gjc: 디렉토리명이 해시다. 프로젝트는 파일 안 cwd 로만 판별 ---
    #   (읽기 좋은 sessions/-projects-<name>/ 은 구형 경로 — 오늘 것은 여기 안 들어온다)
    for p in glob.glob(f"{HOME}/.gjc/agent/sessions/*/*.jsonl"):
        if os.path.getmtime(p) < win_start:
            continue          # cwd 파싱 전에 싸게 거른다
        if _gjc_cwd(p) == project:
            out.append({"store": "gjc", "path": p, "turns": _turns_gjc})

    sessions = []
    for c in out:
        p = c["path"]
        m = os.path.getmtime(p)
        rec = {
            "store": c["store"],
            "sid": os.path.basename(p)[:-6],
            "path": p,
            "mtime": m,
            "size_kb": os.path.getsize(p) // 1024,
            "_turns": c["turns"],
        }
        if not (win_start <= m):
            rec["verdict"] = "skip:창밖"
        elif m > cutoff:
            rec["verdict"] = "skip:작업중"
        else:
            raw = open(p, encoding="utf-8", errors="ignore").read()
            first_user = next((t for r, t in c["turns"](p) if r == "user" and not t.startswith("<")), "")
            rec["first_user"] = first_user[:200]
            if WARP_CALL.search(raw):
                rec["verdict"] = "skip:warp완료"
            elif BOOT_PHRASE.search(first_user):
                rec["verdict"] = "skip:러너/스위퍼"
            else:
                rec["verdict"] = "TARGET"
        sessions.append(rec)

    sessions.sort(key=lambda r: -r["mtime"])
    return sessions


def digest(rec):
    """세션 1개 → 다이제스트 텍스트. user 전문 + assistant 500자 절단."""
    lines = [
        f"# 세션 다이제스트 — {rec['store']}:{short_id(rec['sid'])}",
        "",
        f"- 저장소: `{rec['path']}`",
        f"- 최종 수정: {dt.datetime.fromtimestamp(rec['mtime']):%Y-%m-%d %H:%M}  ({rec['size_kb']}KB)",
        "",
        "> user 발화는 전문, assistant는 500자 절단. thinking·tool_use·tool_result 제외.",
        "",
    ]
    for role, txt in rec["_turns"](rec["path"]):
        if role == "user":
            if txt.startswith("<"):        # system-reminder·cross-session-message 등
                continue
            if txt.startswith(INJECTED_PREFIXES):
                continue
            if len(txt) > USER_CAP:        # 붙여넣기 폭탄·미지의 주입원 방어
                txt = txt[:USER_CAP] + f" …(+{len(txt)-USER_CAP}자 절단)"
            lines.append(f"\n## USER\n{txt}")
        else:
            t = txt[:ASSISTANT_CAP]
            if len(txt) > ASSISTANT_CAP:
                t += f" …(+{len(txt)-ASSISTANT_CAP}자)"
            lines.append(f"\n### assistant\n{t}")
    return "\n".join(lines)


def rejections(rec):
    """(직전 제안, 사람의 기각) 쌍을 뽑는다.

    기각 발화만 떼어놓으면 "무엇을 기각했는지"가 사라지므로 반드시 쌍으로 남긴다 —
    재사용되는 최소 단위가 쌍이다."""
    out, prev = [], None
    for role, txt in rec["_turns"](rec["path"]):
        if role == "user":
            if txt.startswith("<") or txt.startswith(INJECTED_PREFIXES):
                continue
            if (len(txt) <= USER_CAP and REJECT_MARKERS.search(txt)
                    and not APPROVE_HEAD.match(txt)):
                out.append({"proposal": (prev or "")[:400], "rejection": txt[:800]})
        else:
            prev = txt
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", default=os.getcwd())
    ap.add_argument("--since-hours", type=float, default=24)
    ap.add_argument("--exclude-recent-min", type=float, default=60)
    ap.add_argument("--out", default=None, help="기본: research/backlog/sweep/<오늘>")
    ap.add_argument("--now", default=None, help="기준 시각 YYYY-MM-DDTHH:MM (드라이런 시뮬레이션용)")
    ap.add_argument("--dry-run", action="store_true", help="표만 출력, 파일 안 씀")
    a = ap.parse_args()

    now = dt.datetime.fromisoformat(a.now).timestamp() if a.now else dt.datetime.now().timestamp()

    # Failsafe — 창을 "마지막 성공 이후"로 늘린다.
    # 고정 24시간이면 스위퍼가 하루라도 못 뜬 날(맥북이 잠겼거나 실행이 죽었거나)
    # 그 사이 세션이 영영 안 걸린다. 창이 다음 날 이미 지나가 버리기 때문.
    # 마지막 성공 시각을 남겨두고 그 이후 전부를 훑으면 빠뜨림이 사라진다.
    stamp = os.path.join(a.project, "research/backlog/sweep", ".last-success")
    since_h = a.since_hours
    if not a.now and os.path.exists(stamp):
        try:
            last = float(open(stamp, encoding="utf-8").read().strip())
            gap_h = (now - last) / 3600
            if gap_h > since_h:
                since_h = min(gap_h + 1, 24 * 14)   # 상한 2주 — 그 이상은 사람이 볼 일
                print(f"⚠ 마지막 성공이 {gap_h:.1f}시간 전 — 창을 {since_h:.1f}시간으로 넓힘 (건너뛴 날 복구)")
        except Exception as e:
            print(f"⚠ 마지막 성공 시각을 못 읽음({e}) — 기본 창 {since_h}시간으로 진행")

    sessions = discover(a.project, since_h, a.exclude_recent_min, now)
    targets = [s for s in sessions if s["verdict"] == "TARGET"]

    print(f"기준시각 {dt.datetime.fromtimestamp(now):%Y-%m-%d %H:%M} · "
          f"창 {since_h:g}h · 최근 {a.exclude_recent_min:g}분 제외")
    print(f"{'store':7} {'sid':10} {'수정':12} {'크기':>8}  판정")
    for s in sessions:
        print(f"{s['store']:7} {short_id(s['sid']):10} "
              f"{dt.datetime.fromtimestamp(s['mtime']):%m-%d %H:%M}  "
              f"{s['size_kb']:6d}KB  {s['verdict']}")
    by_store = {}
    for s in targets:
        by_store[s["store"]] = by_store.get(s["store"], 0) + 1
    print(f"\n대상 {len(targets)}개 / 스캔 {len(sessions)}개   {by_store}")

    if a.dry_run:
        print("\n(--dry-run: 파일 안 씀)")
        return 0

    date = dt.datetime.fromtimestamp(now).strftime("%Y-%m-%d")
    out = a.out or os.path.join(a.project, "research/backlog/sweep", date)
    os.makedirs(os.path.join(out, "digest"), exist_ok=True)
    index, rej_all = [], []
    for s in targets:
        body = digest(s)
        name = f"{s['store']}-{short_id(s['sid'])}.md"
        with open(os.path.join(out, "digest", name), "w", encoding="utf-8") as fh:
            fh.write(body)
        rj = rejections(s)
        rej_all.append((s, rj))
        index.append({
            "store": s["store"], "sid": s["sid"], "digest": f"digest/{name}",
            "mtime": dt.datetime.fromtimestamp(s["mtime"]).isoformat(timespec="minutes"),
            "size_kb": s["size_kb"], "digest_bytes": len(body.encode()),
            "oversized": len(body.encode()) > DIGEST_CAP,
            "rejections": len(rj),
            "first_user": s.get("first_user", ""),
        })

    # 기각 순간 모음 — 후보만 긁은 것이라 진짜 기각인지는 LLM이 판정한다
    lines = ["# 기각 순간 후보 — 사람이 제안을 되돌린 자리", "",
             "> 어휘로 넓게 긁은 **후보**다(재현율 우선). 진짜 기각인지, 그 안에 담긴 판단 기준이",
             "> 무엇인지는 읽는 쪽이 판정한다. 동의는 정보가 없고 기각에 기준이 압축돼 있다는 전제.", ""]
    for s, rj in rej_all:
        if not rj:
            continue
        lines.append(f"\n## {s['store']}:{short_id(s['sid'])}  ({len(rj)}건)")
        for i, r in enumerate(rj, 1):
            lines.append(f"\n**{i}. 직전 제안** — {r['proposal']}\n\n**→ 사람의 반응** — {r['rejection']}")
    with open(os.path.join(out, "rejections.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    with open(os.path.join(out, "index.json"), "w", encoding="utf-8") as fh:
        json.dump({"generated_for": date, "project": a.project,
                   "scanned": len(sessions), "targets": len(targets),
                   "sessions": index}, fh, ensure_ascii=False, indent=2)
    over = sum(1 for i in index if i["oversized"])
    nrej = sum(i["rejections"] for i in index)
    print(f"\n다이제스트 {len(index)}개 → {out}/digest/   (50KB 초과 {over}개 = 서브에이전트 위임 대상)")
    print(f"기각 순간 후보 {nrej}건 → {out}/rejections.md")

    # 성공 도장은 맨 마지막에 찍는다 — 도중에 죽으면 안 찍히고, 다음 밤이 이번 창까지
    # 다시 훑는다(위 failsafe). 시뮬레이션(--now)은 찍지 않는다.
    if not a.now:
        with open(stamp, "w", encoding="utf-8") as fh:
            fh.write(str(now))
    return 0


if __name__ == "__main__":
    sys.exit(main())
